#include "stdafx.h"
#include "ms_cmu_cmd.h"
#include "ms_pu_param.h"

/*******************************************************************************/
typedef struct _SMsgCmdInfo
{
	unsigned short msg_id;
	unsigned short cmd_id;
	char           msg_name[64];
}SMsgCmdInfo;


SMsgCmdInfo g_msgCmdInfo[] = 
{
	{ MSG_REG,		CMD_REG_REGISTER,					REG_PU_REGISTER},
	{ MSG_REG,		CMD_REG_KEEPALIVE,					REG_PU_KEEPALIVE},

	{ MSG_GET,		CMD_GET_BASICINFO,					GET_PU_BASICINFO},
	{ MSG_GET,		CMD_GET_IPINFO,						GET_PU_IPINFO},
	{ MSG_GET,		CMD_GET_USER,						GET_PU_USER},

	{ MSG_GET,		CMD_GET_SERIALPORT,					GET_PU_SERIALPORT},
	{ MSG_GET,		CMD_GET_INOUTDEV,					GET_PU_INOUTDEV},
	{ MSG_GET,		CMD_GET_TIME,						GET_PU_TIME},

	{ MSG_GET,		CMD_GET_VIDEOFORMAT,		        GET_PU_VIDEOFORMAT},
	{ MSG_GET,		CMD_GET_IMAGEENCODEPARA,		    GET_PU_IMAGEENCODEPARA},
	{ MSG_GET,		CMD_GET_IMAGEDISPLAYPARA,		    GET_PU_IMAGEDISPLAYPARA},
	{ MSG_GET,		CMD_GET_IMAGETEXTPARA,		        GET_PU_IMAGETEXTPARA},

	{ MSG_GET,		CMD_GET_ALARMPARAMS,		        GET_PU_ALARMPARAMS},
	{ MSG_GET,		CMD_GET_GIPINALARM,		            GET_PU_GIPINALARM},

	{ MSG_GET,		CMD_GET_VIDEOLOSE,		            GET_PU_VIDEOLOSE},
	{ MSG_GET,		CMD_GET_HIDEDETECTION,				GET_PU_HIDEDETECTION},
	{ MSG_GET,		CMD_GET_MOTIONDETECTION,			GET_PU_MOTIONDETECTION},
	{ MSG_GET,		CMD_GET_IMAGEHIDEAREA,				GET_PU_IMAGEHIDEAREA},

	{ MSG_GET,		CMD_GET_LOCALSTORAGETASK,		    GET_PU_LOCALSTORAGETASK},

	{ MSG_GET,		CMD_GET_PRESETPTZ,					GET_PU_PRESETPTZ},
	{ MSG_GET,		CMD_GET_DEFAULTPRESETPTZ,		    GET_PU_DEFAULTPRESETPTZ},
	{ MSG_GET,		CMD_GET_CRUISETRACK,				GET_PU_CRUISETRACK},

	{ MSG_GET,		CMD_GET_STATE,						GET_PU_STATE},
	{ MSG_GET,		CMD_GET_LOG,						GET_PU_LOG},

	{ MSG_GET,		CMD_GET_SOFTWAREVERSION,		    GET_PU_SOFTWAREVERSION},
	
	{ MSG_SET,		CMD_SET_BASICINFO,					SET_PU_BASICINFO},
	{ MSG_SET,		CMD_SET_IPINFO,						SET_PU_IPINFO},
	{ MSG_SET,		CMD_SET_USER,						SET_PU_USER},

	{ MSG_SET,		CMD_SET_SERIALPORT,					SET_PU_SERIALPORT},
	{ MSG_SET,		CMD_SET_INOUTDEV,					SET_PU_OUTDEV},
	{ MSG_SET,		CMD_SET_TIME,						SET_PU_TIME},

	{ MSG_SET,		CMD_SET_VIDEOFORMAT,		        SET_PU_VIDEOFORMAT},
	{ MSG_SET,		CMD_SET_IMAGEENCODEPARA,			SET_PU_IMAGEENCODEPARA},
	{ MSG_SET,		CMD_SET_IMAGEDISPLAYPARA,		    SET_PU_IMAGEDISPLAYPARA},
	{ MSG_SET,		CMD_SET_IMAGETEXTPARA,		        SET_PU_IMAGETEXTPARA},

	{ MSG_SET,		CMD_SET_ALARMPARAMS,		        SET_PU_ALARMPARAMS},
	{ MSG_SET,		CMD_SET_GIPINALARM,		            SET_PU_GIPINALARM},

	{ MSG_SET,		CMD_SET_VIDEOLOSE,		            SET_PU_VIDEOLOSE},
	{ MSG_SET,		CMD_SET_HIDEDETECTION,				SET_PU_HIDEDETECTION},
	{ MSG_SET,		CMD_SET_MOTIONDETECTION,		    SET_PU_MOTIONDETECTION},
	{ MSG_SET,		CMD_SET_IMAGEHIDEAREA,				SET_PU_IMAGEHIDEAREA},

	{ MSG_SET,		CMD_SET_LOCALSTORAGETASK,		    SET_PU_LOCALSTORAGETASK},

	{ MSG_SET,		CMD_SET_PRESETPTZ,					SET_PU_PRESETPTZ},
	{ MSG_SET,		CMD_SET_DEFAULTPRESETPTZ,		    SET_PU_DEFAULTPRESETPTZ},
	{ MSG_SET,		CMD_SET_CRUISETRACK,				SET_PU_CRUISETRACK},

	{ MSG_OPER,		CMD_OPER_DELUSER,					OPER_PU_DEL_USER},

	{ MSG_OPER,		CMD_OPER_CLEANPULOCALSTORAGEFILE,	OPER_PU_CLEANPULOCALSTORAGEFILE},
	{ MSG_OPER,		CMD_OPER_QUERYPULOCALSTORAGEFILES,	OPER_PU_QUERYPULOCALSTORAGEFILES},

	{ MSG_OPER,		CMD_OPER_CONTROLPTZ,				OPER_PU_CONTROLPTZ},
	{ MSG_OPER,		CMD_OPER_DELPRESETPTZ,				OPER_PU_DELPRESETPTZ},

	{ MSG_OPER,		CMD_OPER_CONTROLPU,					OPER_PU_CONTROLPU},
	{ MSG_OPER,		CMD_OPER_TRANSPARENTCHANNEL,		OPER_PU_TRANSPARENTCHANNEL},

	{ MSG_UPLOAD,	CMD_UPLOAD_RAISEALARM,				UPLOAD_PU_RAISEALARM},
	{ MSG_UPLOAD,	CMD_UPLOAD_RAISEDIGITAL,			UPLOAD_PU_RAISEDIGITAL},
	{ MSG_OPER,     CMD_OPER_CONTROLFILEBACK ,              OPER_PU_CONTROLFILEBACK}
	
};


int get_msg_cmd_id(unsigned short *msg_id, unsigned short *cmd_id, const char* const_msg_name)
{
	int i = 0, ret = -1;
	for( i=0; i < sizeof(g_msgCmdInfo) / sizeof(SMsgCmdInfo); i++ )
	{
        
		if( strcmp(g_msgCmdInfo[i].msg_name, const_msg_name) == 0 )
		{
//			printf("recv cmd %s\n", g_msgCmdInfo[i].msg_name);
			*msg_id = g_msgCmdInfo[i].msg_id;
			*cmd_id = g_msgCmdInfo[i].cmd_id;
			
			ret = 0;
			break;
		}
	}

	return ret;
}

